apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
