extends: default

rules:
  line-length:
    max: 120 # allowed line length
    level: warning # not an error, but a warning
  document-start:
    present: false # do not require `---` at the beginning
  trailing-spaces:
    level: error # trailing spaces are an error
  new-line-at-end-of-file:
    level: warning # soft recommendation
  braces: disable

ignore: |
  helm/**/templates/*
  helm/values/swagger.yaml
  helm/values/values-dev/swagger.yaml
