apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger.fullname" . }}-config
data:
  swagger.json: |
{{ .Values.swaggerJson | indent 4 }}
  swagger-config.yaml: |
    {
      "url": "/swagger.json"
    }
  swagger-initializer.js: |
    window.onload = function() {
      window.ui = SwaggerUIBundle({
        url: "/swagger.json",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        layout: "StandaloneLayout"
      });
    };
