# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: nginx-deny-all
# spec:
#   podSelector:
#     matchLabels:
#       app: {{ include "nginx.name" . }}
#   policyTypes:
#     - Ingress
#     - Egress
