{{- if .Values.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  .htpasswd: {{ .Values.htpasswd | b64enc }}
{{- end }}
