apiVersion: v2
name: swagger
description: REST API сервис health-api
type: application
version: 1.0.14
appVersion: "1.0.14"
maintainers:
  - name: Vik
    email: viktorgurko@gmail.com
annotations:
  component: swagger
  part-of: health-api
